# Writes BuildInfo.cpp holding the time and number of this build, and counts
# the build in the project's BUILD_NUMBER file.
#
# Run as a script on every build (see the firmware_build_info target in each
# firmware's top-level CMakeLists.txt), not at configure time: a configure-time
# stamp, or __DATE__/__TIME__ in an ordinary source file, only changes when that
# file happens to be recompiled, and so goes stale after incremental builds.
#
# BUILD_NUMBER is committed: every firmware build, an up-to-date one included,
# adds one to it, so the number in an image identifies the build that made it.
#
# Usage: cmake -DOUTPUT=<path/to/BuildInfo.cpp> -DCOUNTER=<path/to/BUILD_NUMBER>
#              -P BuildInfo.cmake

if(NOT OUTPUT)
    message(FATAL_ERROR "BuildInfo.cmake: OUTPUT is not set")
endif()
if(NOT COUNTER)
    message(FATAL_ERROR "BuildInfo.cmake: COUNTER is not set")
endif()

set(BUILD_NUMBER 0)
if(EXISTS "${COUNTER}")
    file(STRINGS "${COUNTER}" COUNTER_LINES LIMIT_COUNT 1)
    if(COUNTER_LINES MATCHES "^[0-9]+$")
        set(BUILD_NUMBER ${COUNTER_LINES})
    else()
        message(FATAL_ERROR "BuildInfo.cmake: ${COUNTER} does not hold a number")
    endif()
endif()
math(EXPR BUILD_NUMBER "${BUILD_NUMBER} + 1")
file(WRITE "${COUNTER}" "${BUILD_NUMBER}\n")

string(TIMESTAMP BUILD_TIME "%Y-%m-%d %H:%M:%S")

file(WRITE "${OUTPUT}"
"// Generated by Common/cmake/BuildInfo.cmake on every build. Do not edit.
#include <Debug/BuildInfo.hpp>

const char* const kFirmwareBuildTime = \"${BUILD_TIME}\";
const uint32_t kFirmwareBuildNumber = ${BUILD_NUMBER}U;
")
message(STATUS "Firmware build ${BUILD_NUMBER}, ${BUILD_TIME}")
