# Writes BuildInfo.cpp holding the time of this build.
#
# Run as a script on every build (see the firmware_build_info target in the
# top-level CMakeLists.txt), not at configure time: a configure-time stamp, or
# __DATE__/__TIME__ in an ordinary source file, only changes when that file
# happens to be recompiled, and so goes stale after incremental builds.
#
# Usage: cmake -DOUTPUT=<path/to/BuildInfo.cpp> -P BuildInfo.cmake

if(NOT OUTPUT)
    message(FATAL_ERROR "BuildInfo.cmake: OUTPUT is not set")
endif()

string(TIMESTAMP BUILD_TIME "%Y-%m-%d %H:%M:%S")

file(WRITE "${OUTPUT}"
"// Generated by cmake/BuildInfo.cmake on every build. Do not edit.
extern const char* const kFirmwareBuildTime;
const char* const kFirmwareBuildTime = \"${BUILD_TIME}\";
")
