#include "st67_mode.h"

#include "main.h"

#define ST67_MANUFACTURE_ENABLE_PULSE_MS 20u
#define ST67_MANUFACTURE_STARTUP_DELAY_MS 20u
#define ST67_BOOTLOADER_ENABLE_PULSE_MS 100u
#define ST67_BOOTLOADER_STRAP_HOLD_MS 100u

void ST67_EnterMode(St67Mode mode)
{
  HAL_GPIO_WritePin(ST67_CHIP_EN_GPIO_Port, ST67_CHIP_EN_Pin, GPIO_PIN_RESET);
  HAL_GPIO_WritePin(ST67_CS_GPIO_Port, ST67_CS_Pin, GPIO_PIN_SET);
  HAL_GPIO_WritePin(ST67_BOOT_GPIO_Port, ST67_BOOT_Pin, GPIO_PIN_RESET);

  switch (mode) {
    case ST67_MODE_MANUFACTURE:
      HAL_Delay(ST67_MANUFACTURE_ENABLE_PULSE_MS);
      HAL_GPIO_WritePin(ST67_CHIP_EN_GPIO_Port, ST67_CHIP_EN_Pin, GPIO_PIN_SET);
      HAL_Delay(ST67_MANUFACTURE_STARTUP_DELAY_MS);
      break;

    case ST67_MODE_BOOTLOADER:
      HAL_GPIO_WritePin(ST67_BOOT_GPIO_Port, ST67_BOOT_Pin, GPIO_PIN_SET);
      HAL_Delay(ST67_BOOTLOADER_ENABLE_PULSE_MS);
      HAL_GPIO_WritePin(ST67_CHIP_EN_GPIO_Port, ST67_CHIP_EN_Pin, GPIO_PIN_SET);
      HAL_Delay(ST67_BOOTLOADER_STRAP_HOLD_MS);
      HAL_GPIO_WritePin(ST67_BOOT_GPIO_Port, ST67_BOOT_Pin, GPIO_PIN_RESET);
      break;

    default:
      Error_Handler();
      break;
  }
}
